kind: Deployment
apiVersion: apps/v1
metadata:
  name: jupyter-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
        - name: jupyter-lab
          image: python-image:latest
          ports:
            - name: http-8888
              containerPort: 8888
              protocol: TCP              
          resources:
            requests:
              memory: "50Mi"
              cpu: "10m"
---
kind: Service
apiVersion: v1
metadata:
  name: jupyter-lab
spec:
ports:
  - name: http-8888
    port: 8888
    protocol: TCP
    targetPort: 8888
selector:
  app: python-app
